# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    ConnectedServiceName: 'ConnResourceManager'
    subscriptionName: 'aafbab9d-6469-4b57-a1ae-fec752258275'
    action: 'Create Or Update Resource Group'
    ResourceGroupName: 'AzureTemplatesForTests'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: 'azuredeploy.json'
    deploymentMode: 'Incremental'
    adminUsername: 'AdminTklaw'
    adminPassword: 'Passw0rd!'



